# Generated by Django 5.0.3 on 2024-04-03 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobapp', '0017_remove_job_category_delete_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='job_type',
            field=models.CharField(choices=[('1', 'MISAC'), ('2', 'FISAC'), ('3', 'Midsem')], max_length=1),
        ),
    ]
